In [2]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

In [11]:
a = np.array([2,3,4])
print a.dtype
b = np.array([1.2, 3.5, 5.1])
print b.dtype

int64
float64


In [12]:
a = np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [14]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [15]:
b = np.array([(1.5,2,3), (4,5,6)])
print b
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print c

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


In [16]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.empty( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [3]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [4]:
np.arange( 0, 2, 0.3 )

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [5]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [6]:
x = np.linspace( 0, 2*pi, 100 )
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [7]:
f = np.sin(x)
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [8]:
a = np.arange(6)                         # 1d array
a

array([0, 1, 2, 3, 4, 5])

In [9]:
b = np.arange(12).reshape(4,3)           # 2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
c = np.arange(24).reshape(2,3,4)         # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [12]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [13]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [15]:
c = a-b
c

array([20, 29, 38, 47])

In [16]:
b**2

array([0, 1, 4, 9])

In [17]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [18]:
a<35

array([ True,  True, False, False], dtype=bool)

In [19]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B

array([[2, 0],
       [0, 4]])

In [20]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [21]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [22]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [24]:
b += a
b

array([[ 6.28332866,  6.6362827 ,  6.48294935],
       [ 6.85447193,  6.93552467,  6.893255  ]])

In [25]:
a += b
a

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [26]:
a = np.ones(3, dtype=np.int32)
a

array([1, 1, 1], dtype=int32)

In [27]:
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [28]:
c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [30]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [31]:
a = np.random.random((2,3))
a

array([[ 0.92017114,  0.63927964,  0.74483341],
       [ 0.71225566,  0.72044004,  0.96966913]])

In [32]:
a.min()

0.63927964133360671

In [33]:
a.max()

0.96966913445776803

In [34]:
a.mean()

0.78444150287478509

In [35]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [37]:
b.min(axis=1)

array([0, 4, 8])

In [38]:
b.sum()

66

In [39]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [40]:
B = np.arange(3)
B

array([0, 1, 2])

In [41]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [42]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [43]:
C = np.array([2., -1., 4.])
C

array([ 2., -1.,  4.])

In [44]:
np.add(B, C)

array([ 2.,  0.,  6.])

In [45]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [46]:
print a[2]
print a[2:5]

8
[ 8 27 64]


In [47]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [48]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [49]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Users/shangbin01/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [50]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [51]:
b[2,3]

23

In [52]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [53]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [54]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [55]:
b[-1]

array([40, 41, 42, 43])

In [56]:
c = np.array( [[[  0,  1,  2],
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
print c.shape
print c[1,...]

(2, 2, 3)
[[100 101 102]
 [110 112 113]]


In [57]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [58]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [59]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [60]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 0.,  6.,  0.,  3.],
       [ 1.,  3.,  4.,  4.],
       [ 1.,  1.,  9.,  4.]])

In [61]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 9.,  2.],
       [ 7.,  3.]])

In [62]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 9.,  9.],
       [ 7.,  9.]])

In [63]:
np.vstack((a,b))

array([[ 9.,  2.],
       [ 7.,  3.],
       [ 9.,  9.],
       [ 7.,  9.]])

In [64]:
np.hstack((a,b))

array([[ 9.,  2.,  9.,  9.],
       [ 7.,  3.,  7.,  9.]])

In [65]:
from numpy import newaxis
np.column_stack((a,b))

array([[ 9.,  2.,  9.,  9.],
       [ 7.,  3.,  7.,  9.]])

In [68]:
a = np.array([4.,2.])
b = np.array([3.,8.])
print np.column_stack((a,b))
print np.vstack((a,b))
print np.hstack((a,b))

[[ 4.  3.]
 [ 2.  8.]]
[[ 4.  2.]
 [ 3.  8.]]
[ 4.  2.  3.  8.]


In [69]:
a[:,newaxis]

array([[ 4.],
       [ 2.]])

In [70]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  3.],
       [ 2.,  8.]])

In [71]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  3.],
       [ 2.,  8.]])

In [72]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])